#ifndef LEDMATRIX_H_
#define LEDMATRIX_H_

#define DISPLAY_COLUMNS (64)
#define DISPLAY_ROWS (32)
#define DISPLAY_PIXELS (DISPLAY_COLUMNS * DISPLAY_ROWS)
#define DISPLAY_INDICES (DISPLAY_PIXELS / 2)

void LEDMATRIX_vInit(void);

#endif
