#ifndef SPRITE_H_
#define SPRITE_H_

#define RED_SIZE (16)
MAIN_tsColour SPRITE_sRed_0[RED_SIZE * RED_SIZE];
MAIN_tsColour SPRITE_sRed_1[RED_SIZE * RED_SIZE];
MAIN_tsColour SPRITE_sRed_2[RED_SIZE * RED_SIZE];

#define PIKACHU_SIZE (16)
MAIN_tsColour SPRITE_sPikachu_0[PIKACHU_SIZE * PIKACHU_SIZE];
MAIN_tsColour SPRITE_sPikachu_1[PIKACHU_SIZE * PIKACHU_SIZE];
MAIN_tsColour SPRITE_sPikachu_2[PIKACHU_SIZE * PIKACHU_SIZE];

#define AGUMON_SIZE (16)
MAIN_tsColour SPRITE_sAgumon_0[AGUMON_SIZE * AGUMON_SIZE];
MAIN_tsColour SPRITE_sAgumon_1[AGUMON_SIZE * AGUMON_SIZE];

#define DIGIMON_1_WIDTH (13)
#define DIGIMON_1_HEIGHT (10)
MAIN_tsColour SPRITE_sDigimon1_0[DIGIMON_1_WIDTH * DIGIMON_1_HEIGHT];
MAIN_tsColour SPRITE_sDigimon1_1[DIGIMON_1_WIDTH * DIGIMON_1_HEIGHT];

#define DIGIMON_2_SIZE (16)
MAIN_tsColour SPRITE_sDigimon2_0[DIGIMON_2_SIZE * DIGIMON_2_SIZE];
MAIN_tsColour SPRITE_sDigimon2_1[DIGIMON_2_SIZE * DIGIMON_2_SIZE];

#define EGG_SIZE (14)
MAIN_tsColour SPRITE_sEgg[EGG_SIZE * EGG_SIZE];

void SPRITE_vInit(void);

#endif
