/*
 * Sprite.c
 *
 *  Created on: 27 Apr 2020
 *      Author: Tim
 */

#include "main.h"
#include "Sprite.h"
#include <string.h> /* memcpy */

/*
 * A set of short hands for drawing sprites
 */
#define RED (MAIN_sRed)
#define GRN (MAIN_sGreen)
#define BLU (MAIN_sBlue)
#define PUR (MAIN_sPurple)
#define YEL (MAIN_sYellow)
#define WHT (MAIN_sWhite)
#define PNK (MAIN_sPink)
#define BLK (MAIN_sBlack)
#define OFF (MAIN_sTransparent)

/**
 * Called before the sprite module can be used
 */
void SPRITE_vInit(void) {
	MAIN_sRed.red = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sRed.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sRed.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sRed.visible = COLOUR_VISIBLE;
	MAIN_sGreen.red = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sGreen.green = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sGreen.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sGreen.visible = COLOUR_VISIBLE;
	MAIN_sBlue.red = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sBlue.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sBlue.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sBlue.visible = COLOUR_VISIBLE;
	MAIN_sPurple.red = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sPurple.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sPurple.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sYellow.red = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sYellow.green = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sYellow.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sYellow.visible = COLOUR_VISIBLE;
	MAIN_sPurple.visible = COLOUR_VISIBLE;
	MAIN_sWhite.red = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sWhite.green = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sWhite.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sWhite.visible = COLOUR_VISIBLE;
	MAIN_sPink.red = COLOUR_BRIGHTNESS_100_PERCENT;
	MAIN_sPink.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sPink.blue = COLOUR_BRIGHTNESS_50_PERCENT;
	MAIN_sPink.visible = COLOUR_VISIBLE;
	MAIN_sBlack.red = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sBlack.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sBlack.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sBlack.visible = COLOUR_VISIBLE;
	MAIN_sTransparent.red = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sTransparent.green = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sTransparent.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	MAIN_sTransparent.visible = COLOUR_INVISIBLE;

	/*
	 * IDE hint: click on a colour, the syntax highlighting will make the sprite somewhat visible
	 */

	/*
	 * Draw Red
	 */
	MAIN_tsColour sRed_0[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		OFF, WHT, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, BLK, BLK, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF
	};
	MAIN_tsColour sRed_1[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		WHT, BLK, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, RED, OFF,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, RED, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF
	};
	MAIN_tsColour sRed_2[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		OFF, RED, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, BLK, WHT, OFF, OFF
	};

	/*
	 * Draw Pikachu
	 */
	MAIN_tsColour sPikachu_0[PIKACHU_SIZE * PIKACHU_SIZE] = {
		OFF, WHT, WHT, WHT, OFF, OFF, OFF, WHT, BLK, WHT, OFF, WHT, WHT, WHT, OFF, OFF,
		WHT, BLK, BLK, BLK, WHT, OFF, WHT, BLK, YEL, BLK, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, BLK, YEL, YEL, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, WHT, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, WHT, WHT, WHT, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};
	MAIN_tsColour sPikachu_1[PIKACHU_SIZE * PIKACHU_SIZE] = {
		WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, WHT, WHT, WHT, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, BLK, BLK, WHT,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK,
		OFF, OFF, WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, YEL, YEL, BLK, WHT,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, YEL, YEL, BLK,
		OFF, WHT, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, YEL, BLK, WHT,
		OFF, WHT, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};
	MAIN_tsColour sPikachu_2[PIKACHU_SIZE * PIKACHU_SIZE] = {
		WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, WHT, WHT, WHT, BLK, YEL, BLK, BLK, WHT, OFF,
		BLK, BLK, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		YEL, YEL, YEL, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		BLK, YEL, YEL, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF, OFF, OFF,
		WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		BLK, BLK, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, WHT, OFF, OFF,
		YEL, YEL, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		BLK, YEL, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		WHT, BLK, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, BLK, BLK, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, YEL, YEL, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, WHT, WHT, WHT, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};

	/*
	 * Draw Agumon
	 */
    MAIN_tsColour sAgumon_0[AGUMON_SIZE * AGUMON_SIZE] = {
        OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, OFF, OFF, BLU, BLU, BLU, BLU, BLU, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, BLU, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF, OFF, OFF,
        OFF, OFF, BLU, BLU, WHT, WHT, BLU, WHT, WHT, BLU, BLU, BLU, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, WHT, BLU, BLU, WHT, BLU, OFF, OFF,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, BLU, OFF,
        BLU, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, OFF, OFF,
        OFF, OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, WHT, BLU, OFF, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, BLU, BLU, BLU, WHT, BLU, WHT, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU,
        OFF, BLU, WHT, BLU, WHT, BLU, BLU, WHT, WHT, WHT, BLU, WHT, BLU, WHT, BLU, WHT,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT
    };
    MAIN_tsColour sAgumon_1[AGUMON_SIZE * AGUMON_SIZE] = {
        OFF, OFF, OFF, OFF, OFF, OFF, BLU, BLU, BLU, BLU, BLU, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, BLU, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF, OFF, OFF,
        OFF, OFF, BLU, BLU, WHT, WHT, BLU, WHT, WHT, BLU, BLU, BLU, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, WHT, BLU, BLU, WHT, BLU, OFF, OFF,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, BLU, OFF,
        BLU, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, OFF, OFF,
        OFF, OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, WHT, BLU, OFF, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, WHT, WHT, BLU, WHT, BLU, OFF,
        OFF, OFF, OFF, BLU, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        OFF, OFF, BLU, WHT, WHT, BLU, BLU, WHT, WHT, WHT, WHT, BLU, BLU, BLU, WHT, BLU,
        OFF, BLU, WHT, BLU, WHT, BLU, BLU, WHT, BLU, WHT, BLU, WHT, BLU, WHT, BLU, WHT,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT
    };
    MAIN_tsColour sAgumon_2[AGUMON_SIZE * AGUMON_SIZE] = {
        OFF, OFF, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, OFF, OFF, OFF, OFF, OFF,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, OFF, OFF, OFF,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, WHT, BLU, BLU, WHT, OFF, OFF,
        BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, BLU, BLU, WHT, WHT, BLU, WHT, OFF, OFF,
        OFF, BLU, BLU, WHT, WHT, WHT, WHT, WHT, BLU, WHT, WHT, WHT, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, BLU, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, WHT, BLU, BLU, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, BLU, WHT, BLU, WHT, BLU, OFF, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, WHT, WHT, BLU, WHT, BLU, OFF,
        OFF, OFF, OFF, BLU, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        OFF, OFF, BLU, WHT, WHT, BLU, BLU, WHT, WHT, WHT, WHT, BLU, BLU, BLU, WHT, BLU,
        OFF, BLU, WHT, BLU, WHT, BLU, BLU, WHT, BLU, WHT, BLU, WHT, BLU, WHT, BLU, WHT,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT
    };

    /*
     * Draw Digimon 1
     */
    MAIN_tsColour sDigimon1_0[DIGIMON_1_WIDTH * DIGIMON_1_HEIGHT] = {
        OFF, OFF, OFF, BLU, BLU, OFF, OFF, OFF, BLU, BLU, OFF, OFF, OFF,
        OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, WHT, WHT, BLU, OFF, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, WHT, WHT, BLU, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        BLU, WHT, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLU, OFF, OFF,

    };
    MAIN_tsColour sDigimon1_1[DIGIMON_1_WIDTH * DIGIMON_1_HEIGHT] = {
        OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, BLU, BLU, OFF, OFF, OFF, BLU, BLU, OFF, OFF, OFF,
        OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, WHT, WHT, BLU, OFF, OFF,
        OFF, OFF, BLU, WHT, BLU, WHT, WHT, WHT, BLU, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU, OFF,
        BLU, WHT, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, WHT, BLU, BLU, BLU, WHT, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, BLU, BLU, WHT, BLU, BLU, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU, WHT, BLU,
        OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLU, OFF
    };

    /*
     * Draw Egg
     */
    MAIN_tsColour sEgg[EGG_SIZE * EGG_SIZE] = {
        OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, OFF, BLU, BLU, BLU, BLU, OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, OFF, BLU, WHT, WHT, WHT, WHT, BLU, OFF, OFF, OFF, OFF,
        OFF, OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, WHT, BLU, OFF, OFF, OFF,
        OFF, OFF, BLU, WHT, WHT, WHT, BLU, BLU, WHT, WHT, WHT, BLU, OFF, OFF,
        OFF, BLU, WHT, WHT, WHT, BLU, BLU, BLU, WHT, WHT, WHT, WHT, BLU, OFF,
        OFF, BLU, WHT, BLU, BLU, BLU, BLU, BLU, WHT, WHT, WHT, WHT, BLU, OFF,
        BLU, WHT, BLU, BLU, WHT, BLU, BLU, BLU, BLU, WHT, WHT, WHT, WHT, BLU,
        BLU, WHT, BLU, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, WHT, WHT, BLU,
        BLU, WHT, BLU, BLU, WHT, WHT, WHT, BLU, BLU, BLU, BLU, BLU, WHT, BLU,
        BLU, WHT, BLU, BLU, BLU, WHT, WHT, BLU, BLU, WHT, WHT, BLU, WHT, BLU,
        OFF, BLU, WHT, WHT, BLU, BLU, BLU, BLU, WHT, WHT, WHT, WHT, BLU, OFF,
        OFF, OFF, BLU, WHT, WHT, BLU, BLU, BLU, WHT, WHT, WHT, BLU, OFF, OFF,
        OFF, OFF, OFF, BLU, WHT, WHT, WHT, WHT, WHT, WHT, BLU, OFF, OFF, OFF
    };


    /*
     * Draw Background graphic
     */
    MAIN_tsColour sBackground[BACKGROUND_WIDTH * BACKGROUND_HEIGHT] = {
        BLU, BLU, BLU, BLU, BLU,
        BLU, OFF, OFF, OFF, BLU,
        BLU, BLU, BLU, OFF, BLU,
        OFF, OFF, OFF, OFF, BLU,
        BLU, BLU, BLU, BLU, BLU,
        BLU, OFF, OFF, OFF, OFF,
        BLU, OFF, BLU, BLU, BLU,
        BLU, OFF, OFF, OFF, BLU,
        BLU, BLU, BLU, BLU, BLU,
        OFF, OFF, OFF, OFF, OFF,
        BLU, BLU, BLU, BLU, BLU,
        BLU, OFF, BLU, OFF, BLU,
        BLU, OFF, OFF, OFF, BLU,
        BLU, BLU, BLU, BLU, BLU,
        OFF, OFF, BLU, OFF, OFF,
        BLU, OFF, BLU, OFF, BLU,
        BLU, BLU, BLU, BLU, BLU,
        OFF, OFF, OFF, OFF, OFF,
        BLU, BLU, BLU, BLU, BLU,
        OFF, BLU, OFF, OFF, BLU,
        OFF, OFF, BLU, OFF, BLU,
        OFF, OFF, OFF, BLU, BLU,
        OFF, OFF, OFF, OFF, BLU,
        OFF, OFF, OFF, OFF, OFF,
        OFF, OFF, BLU, OFF, OFF,
        BLU, BLU, BLU, BLU, OFF,
        BLU, OFF, BLU, OFF, BLU,
        BLU, BLU, BLU, BLU, BLU,
        OFF, OFF, BLU, OFF, BLU,
        OFF, OFF, OFF, OFF, OFF
    };

	memcpy(SPRITE_sRed_0, sRed_0, sizeof sRed_0);
	memcpy(SPRITE_sRed_1, sRed_1, sizeof sRed_1);
	memcpy(SPRITE_sRed_2, sRed_2, sizeof sRed_2);
	memcpy(SPRITE_sPikachu_0, sPikachu_0, sizeof sPikachu_0);
	memcpy(SPRITE_sPikachu_1, sPikachu_1, sizeof sPikachu_1);
	memcpy(SPRITE_sPikachu_2, sPikachu_2, sizeof sPikachu_2);
    memcpy(SPRITE_sAgumon_0, sAgumon_0, sizeof sAgumon_0);
    memcpy(SPRITE_sAgumon_1, sAgumon_1, sizeof sAgumon_1);
    memcpy(SPRITE_sAgumon_2, sAgumon_2, sizeof sAgumon_2);
    memcpy(SPRITE_sDigimon1_0, sDigimon1_0, sizeof sDigimon1_0);
    memcpy(SPRITE_sDigimon1_1, sDigimon1_1, sizeof sDigimon1_1);
    memcpy(SPRITE_sEgg, sEgg, sizeof sEgg);
    memcpy(SPRITE_sBackground, sBackground, sizeof sBackground);
}
