/*
 * Sprite.c
 *
 *  Created on: 27 Apr 2020
 *      Author: Tim
 */

#include "main.h"
#include "Sprite.h"
#include <string.h> /* memcpy */

#define COLOUR_BRIGHTNESS_100_PERCENT (4)
#define COLOUR_BRIGHTNESS_75_PERCENT  (3)
#define COLOUR_BRIGHTNESS_50_PERCENT  (2)
#define COLOUR_BRIGHTNESS_25_PERCENT  (1)
#define COLOUR_BRIGHTNESS_0_PERCENT   (0)
#define COLOUR_VISIBLE (1)
#define COLOUR_INVISIBLE (0)

void SPRITE_vInit(void) {

	SPRITE_sRed.red = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sRed.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sRed.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sRed.visible = COLOUR_VISIBLE;
	SPRITE_sGreen.red = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sGreen.green = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sGreen.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sGreen.visible = COLOUR_VISIBLE;
	SPRITE_sBlue.red = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sBlue.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sBlue.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sBlue.visible = COLOUR_VISIBLE;
	SPRITE_sPurple.red = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sPurple.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sPurple.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sYellow.red = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sYellow.green = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sYellow.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sYellow.visible = COLOUR_VISIBLE;
	SPRITE_sPurple.visible = COLOUR_VISIBLE;
	SPRITE_sWhite.red = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sWhite.green = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sWhite.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sWhite.visible = COLOUR_VISIBLE;
	SPRITE_sPink.red = COLOUR_BRIGHTNESS_100_PERCENT;
	SPRITE_sPink.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sPink.blue = COLOUR_BRIGHTNESS_50_PERCENT;
	SPRITE_sPink.visible = COLOUR_VISIBLE;
	SPRITE_sBlack.red = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sBlack.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sBlack.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sBlack.visible = COLOUR_VISIBLE;
	SPRITE_sTransparent.red = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sTransparent.green = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sTransparent.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	SPRITE_sTransparent.visible = COLOUR_INVISIBLE;

	/*
	 * IDE hint: click on a colour, the syntax highlighting will make the sprite somewhat visible
	 */

	/*
	 * Draw Red
	 */
	MAIN_tsColour sRed_0[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		OFF, WHT, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, BLK, BLK, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF
	};
	MAIN_tsColour sRed_1[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		WHT, BLK, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, RED, OFF,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, RED, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF
	};
	MAIN_tsColour sRed_2[RED_SIZE * RED_SIZE] = {
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, OFF,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		OFF, RED, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, RED, BLK, BLK, BLK, WHT, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, BLK, WHT, OFF, OFF
	};

	/*
	 * Draw Pikachu
	 */
	MAIN_tsColour sPikachu_0[PIKACHU_SIZE * PIKACHU_SIZE] = {
		OFF, WHT, WHT, WHT, OFF, OFF, OFF, WHT, BLK, WHT, OFF, WHT, WHT, WHT, OFF, OFF,
		WHT, BLK, BLK, BLK, WHT, OFF, WHT, BLK, YEL, BLK, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, BLK, YEL, YEL, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, WHT, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, WHT, WHT, WHT, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};
	MAIN_tsColour sPikachu_1[PIKACHU_SIZE * PIKACHU_SIZE] = {
		WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, WHT, WHT, WHT, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, BLK, BLK, WHT,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK,
		OFF, OFF, WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, YEL, YEL, BLK, WHT,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, BLK, BLK, WHT,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, YEL, YEL, BLK,
		OFF, WHT, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, YEL, BLK, WHT,
		OFF, WHT, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, BLK, WHT, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, BLK, BLK, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};
	MAIN_tsColour sPikachu_2[PIKACHU_SIZE * PIKACHU_SIZE] = {
		WHT, BLK, BLK, BLK, WHT, OFF, OFF, OFF, OFF, OFF, WHT, BLK, BLK, BLK, WHT, OFF,
		WHT, BLK, BLK, YEL, BLK, WHT, WHT, WHT, WHT, WHT, BLK, YEL, BLK, BLK, WHT, OFF,
		BLK, BLK, BLK, YEL, YEL, BLK, BLK, BLK, BLK, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		YEL, YEL, YEL, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		BLK, YEL, YEL, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, BLK, WHT, OFF, OFF, OFF,
		WHT, BLK, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, YEL, BLK, WHT, OFF, OFF, OFF,
		BLK, BLK, BLK, YEL, BLK, YEL, BLK, BLK, BLK, YEL, BLK, YEL, BLK, WHT, OFF, OFF,
		YEL, YEL, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		BLK, YEL, BLK, YEL, YEL, BLK, YEL, YEL, YEL, BLK, YEL, YEL, BLK, WHT, OFF, OFF,
		WHT, BLK, BLK, YEL, BLK, BLK, YEL, YEL, YEL, BLK, BLK, YEL, BLK, WHT, OFF, OFF,
		OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, YEL, BLK, WHT, OFF, OFF,
		OFF, OFF, WHT, BLK, YEL, YEL, YEL, YEL, YEL, BLK, BLK, BLK, WHT, OFF, OFF, OFF,
		OFF, OFF, OFF, WHT, BLK, BLK, BLK, BLK, BLK, YEL, YEL, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, WHT, WHT, WHT, WHT, WHT, BLK, BLK, WHT, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, WHT, WHT, OFF, OFF, OFF, OFF, OFF,
		OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
	};
	memcpy(SPRITE_sRed_0, sRed_0, sizeof sRed_0);
	memcpy(SPRITE_sRed_1, sRed_1, sizeof sRed_1);
	memcpy(SPRITE_sRed_2, sRed_2, sizeof sRed_2);
	memcpy(SPRITE_sPikachu_0, sPikachu_0, sizeof sPikachu_0);
	memcpy(SPRITE_sPikachu_1, sPikachu_1, sizeof sPikachu_1);
	memcpy(SPRITE_sPikachu_2, sPikachu_2, sizeof sPikachu_2);
}
