/*
 * Sprite.c
 *
 *  Created on: 27 Apr 2020
 *      Author: Tim
 */

#include "main.h"
#include "Sprite.h"
#include <string.h> /* memcpy */

#define COLOUR_BRIGHTNESS_100_PERCENT (4)
#define COLOUR_BRIGHTNESS_75_PERCENT  (3)
#define COLOUR_BRIGHTNESS_50_PERCENT  (2)
#define COLOUR_BRIGHTNESS_25_PERCENT  (1)
#define COLOUR_BRIGHTNESS_0_PERCENT   (0)

void SPRITE_vInit(void) {

	GRAPHICS_tsRed.red = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsRed.green = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsRed.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsGreen.red = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsGreen.green = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsGreen.blue = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlue.red = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlue.green = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlue.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsPurple.red = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsPurple.green = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsPurple.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsWhite.red = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsWhite.green = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsWhite.blue = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsPink.red = COLOUR_BRIGHTNESS_100_PERCENT;
	GRAPHICS_tsPink.green = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlack.blue = COLOUR_BRIGHTNESS_50_PERCENT;
	GRAPHICS_tsBlack.red = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlack.green = COLOUR_BRIGHTNESS_0_PERCENT;
	GRAPHICS_tsBlack.blue = COLOUR_BRIGHTNESS_0_PERCENT;

	/*
	 * IDE hint: click on a colour, the syntax highlighting will make the sprite somewhat visible
	 */

	MAIN_tsColour sRed_0[RED_SIZE * RED_SIZE] = {
		WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, WHT,
		WHT, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, WHT,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		WHT, WHT, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, WHT, WHT,
		WHT, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, WHT,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT,
		WHT, WHT, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, BLK, BLK, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, BLK, BLK, BLK, WHT, WHT, BLK, BLK, BLK, WHT, WHT, WHT, WHT
	};
	MAIN_tsColour sRed_1[RED_SIZE * RED_SIZE] = {
		WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, WHT,
		WHT, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, WHT,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		WHT, BLK, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, RED, WHT,
		WHT, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, WHT,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, BLK, WHT,
		WHT, WHT, BLK, BLK, BLK, RED, BLK, BLK, BLK, BLK, BLK, WHT, WHT, BLK, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, BLK, BLK, RED, RED, BLK, BLK, BLK, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT
	};
	MAIN_tsColour sRed_2[RED_SIZE * RED_SIZE] = {
		WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, RED, RED, RED, RED, RED, RED, RED, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, BLK, BLK, BLK, RED, WHT, WHT, WHT, WHT, RED, BLK, BLK, BLK, WHT, WHT,
		WHT, WHT, BLK, BLK, WHT, BLK, BLK, BLK, BLK, BLK, BLK, WHT, BLK, BLK, WHT, WHT,
		WHT, BLK, WHT, BLK, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, BLK, WHT, BLK, WHT,
		WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, WHT, WHT, BLK, WHT,
		WHT, RED, BLK, BLK, WHT, WHT, BLK, WHT, WHT, BLK, WHT, WHT, BLK, BLK, BLK, WHT,
		WHT, WHT, BLK, BLK, BLK, WHT, WHT, RED, RED, WHT, WHT, BLK, BLK, BLK, WHT, WHT,
		WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, BLK, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, WHT,
		WHT, WHT, BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, RED, BLK, BLK, BLK, WHT, WHT,
		WHT, WHT, WHT, BLK, BLK, BLK, BLK, RED, RED, BLK, BLK, RED, BLK, WHT, WHT, WHT,
		WHT, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, BLK, WHT, WHT, WHT
	};
	memcpy(SPRITE_sRed_0, sRed_0, sizeof sRed_0);
	memcpy(SPRITE_sRed_1, sRed_1, sizeof sRed_1);
	memcpy(SPRITE_sRed_2, sRed_2, sizeof sRed_2);
}
